const Fakenillas = [
  {
    id: 1,
    title: 'Planilla 1',
    description: 'Descripción de la planilla 1',
    date: '2024-08-07',
    status: 'Completado',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 2,
    title: 'Planilla 2',
    description: 'Descripción de la planilla 2',
    date: '2024-08-08',
    status: 'Pendiente',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 3,
    title: 'Planilla 3',
    description: 'Descripción de la planilla 3',
    date: '2024-08-07',
    status: 'Completado',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 4,
    title: 'Planilla 4',
    description: 'Descripción de la planilla 4',
    date: '2024-08-08',
    status: 'Pendiente',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 5,
    title: 'Planilla 5',
    description: 'Descripción de la planilla 5',
    date: '2024-08-07',
    status: 'Completado',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 6,
    title: 'Planilla 6',
    description: 'Descripción de la planilla 6',
    date: '2024-08-08',
    status: 'Pendiente',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 7,
    title: 'Planilla 7',
    description: 'Descripción de la planilla 7',
    date: '2024-08-07',
    status: 'Completado',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 8,
    title: 'Planilla 8',
    description: 'Descripción de la planilla 8',
    date: '2024-08-08',
    status: 'Pendiente',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 9,
    title: 'Planilla 9',
    description: 'Descripción de la planilla 9',
    date: '2024-08-07',
    status: 'Completado',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
  {
    id: 10,
    title: 'Planilla 10',
    description: 'Descripción de la planilla 10',
    date: '2024-08-08',
    status: 'Pendiente',
    steps: [
      {
        numero: 1,
        consigna: 'Consigna del step 1',
        tipoRespuesta: 'Texto',
        obligatorio: true,
        isEnabled: true,
      },
      {
        numero: 2,
        consigna: 'Consigna del step 2',
        tipoRespuesta: 'Selección múltiple',
        obligatorio: false,
        isEnabled: true,
      },
    ],
  },
];

export default Fakenillas;